### ISSUE TITLE
Some symbols in Friluftsliv, punkter does not work

### ISSUE THREAD

**Issue by hblGP** [GeoDanmarkGeoFA/QGIS_GeoFA#2]
**Describe the bug**
Errors in GeoFA symbols for outdoor activities, points. Unfortunately, it seems that after the plugin has been added to the QGIS repository, some symbols with ØÆÅ in their names are not functioning. QGIS, in general, doesn't handle our ØÆÅ characters well, so I suggest renaming all symbols so that these characters are not used.

**Comment by hvingel-l** [comment]
Icons are being renamed (in process)

**Comment by hblGP** [comment]
Solved in V. 0.2
