### ISSUE TITLE
Froms dialog can become too long

### ISSUE THREAD

**Issue by hblGP** [GeoDanmarkGeoFA/QGIS_GeoFA#3]
**Describe the bug**
For some users that use a small screen the QGIS forms dialog, can get too long, so they are not abel to press okay. Resizing can cause issues as well where the dialog just disappear. 

This is especially a problem with Friluftsliv, linjer. A suggestion could be to create tabs in the forms dialog instead, this would make the forms dialog smaller.

**Comment by hvingel-l** [comment]
Could "scroll-down" be implemented? (in stead of tabs)

**Comment by hblGP** [comment]
> Could "scroll-down" be implemented? (in stead of tabs)

Sadly as far as i know this is not currently possible in the long term release of QGIS.

**Comment by hblGP** [comment]
Solved in V 0.2. Only added the tabs for Friluftsliv, linjer. Could add more if users experience problems with other layers.
